version: '3.8'

services:

  customer-service:
    build: ./customer-service
    container_name: customer_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - loan-verification-service
      - risk-assessment-service  
    environment:
      DB_USER: user1
      DB_PASS: password1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: loans_db

  loan-verification-service:
    build: ./loan-verification-service
    container_name: loan_verification_service
    ports:
      - "8001:8001"

  risk-assessment-service:  
    build: ./risk-assessment-service
    container_name: risk_assessment_service
    ports:
      - "50051:50051"

  postgres:
    image: postgres:15
    container_name: loan_postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: loans_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
