version: '3.8'

services:

  customer-service:
    build: ./customer-service
    container_name: customer_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - loan-verification-service
      - risk-assessment-service 
      - check-validation-service
      - notification-service 
    environment:
      DB_USER: user1
      DB_PASS: password1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: loans_db
    networks:
      - loan-net

  loan-verification-service:
    build: ./loan-verification-service
    container_name: loan_verification_service
    ports:
      - "8001:8001"
    networks:
      - loan-net
    
  check-validation-service:
    build: ./check-validation-service
    container_name: check_validation_service
    ports:
      - "8002:8002"
    depends_on:
      - bank-service
    networks:
      - loan-net

  risk-assessment-service:  
    build: ./risk-assessment-service
    container_name: risk_assessment_service
    ports:
      - "50051:50051"
    networks:
      - loan-net

  notification-service:
    build: ./notification-service
    container_name: notification_service
    ports:
      - "8003:8003"
    networks:
      - loan-net

  bank-service:
    build: ./bank-service
    container_name: bank_service
    ports:
      - "8004:8004"
    networks:
      - loan-net

  postgres:
    image: postgres:15
    container_name: loan_postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: loans_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loan-net

volumes:
  pgdata:

networks:
  loan-net:
    external: true